export const WINE_TYPES = {
  red: { label: 'Rosso', badge: 'badge-red' },
  white: { label: 'Bianco', badge: 'badge-white' },
  rose: { label: 'Rosé', badge: 'badge-rose' },
  sparkling: { label: 'Spumante', badge: 'badge-sparkling' },
}

export const REGIONS = [
  'Piemonte',
  'Toscana',
  'Veneto',
  'Friuli-Venezia Giulia',
  'Alto Adige',
  'Lombardia',
  'Sicilia',
  'Puglia',
  'Campania',
  'Sardegna',
  'Emilia-Romagna',
  'Umbria',
  'Marche',
  'Abruzzo',
  'Lazio',
  'Trentino',
  'Liguria',
  'Calabria',
  'Basilicata',
  'Valle d\'Aosta',
  'Molise',
  // Internazionali
  'Bordeaux',
  'Borgogna',
  'Champagne',
  'Rhône',
  'Alsazia',
  'Loira',
  'Rioja',
  'Ribera del Duero',
  'Napa Valley',
  'Sonoma',
  'Mendoza',
  'Altro',
]

export const mockWines = [
  {
    id: '1',
    name: 'Barolo Riserva',
    producer: 'Giacomo Conterno',
    vintage: 2016,
    type: 'red',
    region: 'Piemonte',
    quantity: 3,
    price: 180,
    position: 'Scaffale A, fila 2',
    notes: 'Nebbiolo in purezza, affinamento 7 anni. Aprire 2025-2040.',
    photo: null,
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    name: 'Brunello di Montalcino',
    producer: 'Biondi-Santi',
    vintage: 2017,
    type: 'red',
    region: 'Toscana',
    quantity: 2,
    price: 120,
    position: 'Scaffale A, fila 3',
    notes: 'Sangiovese Grosso, grande struttura.',
    photo: null,
    createdAt: '2024-02-20T14:00:00Z',
  },
  {
    id: '3',
    name: 'Cervaro della Sala',
    producer: 'Antinori',
    vintage: 2021,
    type: 'white',
    region: 'Umbria',
    quantity: 6,
    price: 45,
    position: 'Scaffale B, fila 1',
    notes: 'Chardonnay e Grechetto, fermentazione in barrique.',
    photo: null,
    createdAt: '2024-03-10T09:15:00Z',
  },
  {
    id: '4',
    name: 'Franciacorta Satèn',
    producer: 'Ca\' del Bosco',
    vintage: 2018,
    type: 'sparkling',
    region: 'Lombardia',
    quantity: 4,
    price: 38,
    position: 'Scaffale C, fila 1',
    notes: 'Chardonnay 100%, dosaggio zero. Perfetto per aperitivo.',
    photo: null,
    createdAt: '2024-03-25T16:45:00Z',
  },
  {
    id: '5',
    name: 'Cerasuolo d\'Abruzzo',
    producer: 'Emidio Pepe',
    vintage: 2022,
    type: 'rose',
    region: 'Abruzzo',
    quantity: 5,
    price: 28,
    position: 'Scaffale B, fila 2',
    notes: 'Montepulciano vinificato in rosa, biodinamico.',
    photo: null,
    createdAt: '2024-04-05T11:20:00Z',
  },
  {
    id: '6',
    name: 'Tignanello',
    producer: 'Antinori',
    vintage: 2019,
    type: 'red',
    region: 'Toscana',
    quantity: 2,
    price: 95,
    position: 'Scaffale A, fila 1',
    notes: 'Sangiovese, Cabernet Sauvignon e Cabernet Franc. Supertuscan storico.',
    photo: null,
    createdAt: '2024-04-18T13:30:00Z',
  },
]

export function generateId() {
  return Math.random().toString(36).substring(2, 11)
}
